image: python:3.13

pipelines:
    branches:
        main:
            - step:
                  script:
                    #   - ls 
                    #   - cp -r ./main_code/* ./build/2024_12_4/
                    #   - cd ./build/2024_12_4/
                    #   - python3 ./encode.py
                    #   - cat manifest.json
                    #   - cd ../../
                    #   - ls ./build/2024_12_4/
                      - rm -rf ./main_code
                      - git add .                 
                      - git commit -m "update code"
                      - git push --all --force git@github.com:javishome/javis_lock.git