name: Create Release 2024_4_4

on:
  push:
    branches:
      - main 
    paths:
      - "build/2024_4_4/**"  
permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from manifest.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' build/2024_4_4/manifest.json)" >> $GITHUB_ENV

      - name: Delete old release and tag (if exists)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release delete "v2024_4_4_${{ env.VERSION }}" --cleanup-tag -y || true

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/build/2024_4_4
          zip -r javis_lock.zip ./

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v2024_4_4_${{ env.VERSION }}"
          release_name: "Release v2024_4_4_${{ env.VERSION }}"
          body: "### Changelog\n\n- Cập nhật v2024_4_4_${{ env.VERSION }}."
          draft: false
          prerelease: false
          files: build/2024_4_4/javis_lock.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}